name: Run Format Linter

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: update-package-lists
        run: |
          sudo apt update

      - name: clnag-format
        run: |
          sudo apt install clang-format-12
          touch .codecheckignore
          find -type f \
            | ( grep '.*\.\(c\|cpp\|h\|hpp\)$' || true ) \
            | while read file; do clang-format-12 -i -style=file "${file}"; done

      - name: Astyle
        run: |
          sudo apt install astyle
          touch .codecheckignore
          find -type f \
            | ( grep '.*\.\(c\|cpp\|h\|hpp\)$' || true ) \
            | while read file; do astyle -n --options=.astylerc "${file}"; done

      - name: Git commmit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Formatting Robot
          author_email: robot@example.com
          message: "[update] format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
